### ISSUE TITLE
美化serv_offers

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#10]
1、格式化
2、分页&分页格式化

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/36fb1a738a696410d907e8ab989fca07a4cf659a)
2.脚本rails g kaminari:config 、rails g kaminari:views bootstrap3、rails g bootstrap:themed Pages
