### ISSUE TITLE
user信息修改

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#18]

**Comment by sguo2017** [comment]
图片字段avatar

**Comment by sguo2017** [comment]
这个issue仅针对页面的用户信息修改

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/f9226f77a438f3205206b4989c39deeebbe5a114)
2.注意：在注册控制器（registrations_controller.rb）修改的Action里（#edit）中根据session重新生成全局对象@user，否则会报错；在前端添加新增字段的表单项，同时在registrations_conttroller.rb中重写current_user返回当前对象（返回@user就好，否则提交修改会报错），并且在私有方法user_params中params.require(:user).permit( :param1,...)中增加允许修改的字段名（否则修改不成功）。
