### ISSUE TITLE
个人图像修改api

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#20]

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/f9226f77a438f3205206b4989c39deeebbe5a114)
2.脚本：
#gem 'carrierwave'>Gemfile
rails g migration add_avatar_to_user avatar:string
rake db:migrate
rails g uploader UserAvatar
3.注意：
（1）由于用户头像的图片在整个Application的layout中都要显示，所以为了方便，直接将image的url放在了session中。
（2）此方案默认上传图片到Web服务器目录下，DB只保存文件名，利用carrierwave映射成avatar对象，但这跟REST API上传方式存在不一致，后面的版本可能会取消这个插件使用其他的方法上传图片。
