### ISSUE TITLE
退出时重定向到登录页面

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#22]

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/7ad54bd4c8774fbae4e5288650c81cccb28f503c)
2.解决方案：在SessionController#destroy中最render语句改为redirect_to(:action=>'new')即可；
3.注意：此版本中提价了REST API方式修改用户头像的相关方法，但是由于一个小问题目前还不可用，将在下个版本修复。
