### ISSUE TITLE
引入cancancan

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#28]
1、引入cancancan;
2、表user增加字段admin类型为boolean缺省值为false;
3、新注册一个用户admin其admin属性为true;
4、用户admin有管理菜单栏user的权限

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/ada101b56cae470cf140fad53e039da3bd225f4b)
2.脚本
rails g migration AddAdminToUser admin:boolean
（执行完上面之后需要在迁移文件里面指定默认值false,即
`add_column :users, :admin, :boolean, default: false`）
rake db:migrate
rails g cancan:ability
