### ISSUE TITLE
查询增加条件区域

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#29]
1、订单、商品、用户增加条件区域，通过设置条件来获取相关数据；
2、同理其他也同时设置条件区域；

**Comment by GreatVincy** [comment]
脚本及步骤：
（1）rails g model ServOffersSearch serv_id:integer user_id:integer serv_title:string serv_detail:string serv_category:string serv_created:string
（2）rake db:mirgrate
（3）rails g controller serv_offers_searches --no-assets --no-helper
（4）resources :serv_offers_searches >> routes.rb
（5）serv_offers_searches_controller 添加create、update、show方法
这里由于serv_offers_searches_controller没有自己的视图而是使用offer_servs/index同时作为搜索的主页和搜索结果的展示页，所以create与update代码相同，都是创建一个ServOffersSearch对象并持久化，然后重定向到show;show要定义@serv_offers_search实例变量供前端表单回显，以及调用model(ServOffersSearch)的条件查询方法查询结果并且定义为@serv_offers供前端视图展示，最后渲染所需的视图（serv_offers/index）
（6）view页面（serv_offer/index）使用form_for @serv_offers_search添加表单，这里把表单抽离出来，使用局部视图渲染
（7）ServOffersSearch类添加serv_offers方法，添加条件查询的实现逻辑
（8）lib目录下建立search.rake增加删除过期搜索记录的rake任务

**Comment by GreatVincy** [comment]
1.最终[版本](https://github.com/sguo2017/tisp_rails_api/commit/2f5ff54e041368311bd98eeecd20d7db0e90f599)

2.为good、chat、favorite、goods_catalog、order、sms_send、sys_msg、user  8个模型增加了搜索功能
3.搜索记录会保存在数据库中，在lib/search.rake文件中定义了8个rake任务用于清除这些数据（TRUNCATE语句），分别执行一下命令即可清除对应表：
> rake clear_goods_searches
> rake clear_chats_searches
> rake clear_favorites_searches
> rake clear_goods_catalogs_searches
> rake clear_orders_searches
> rake clear_sms_sends_searches
> rake clear_sys_msgs_searches
> rake clear_users_searches
