### ISSUE TITLE
界面用户注册走独立的controller

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#31]

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/f5cd3715984f41c8cd96d8c8a94fc4a7011a99c5)
2.解决详情
（1）注册Action（create）里面直接super调用父类方法
（2）保险起见，super调用完之后reset_session清除session缓存
（3）由于session已经清除，所以注册完之后自动重定向到登录页面
