### ISSUE TITLE
API注册用户走独立的controller

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#32]
提供api调用实例

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/f5cd3715984f41c8cd96d8c8a94fc4a7011a99c5)
2.解决详情
（1）将API注册的控制器放放到了app/controllers/api/session/users_controller的create方法下（POST访问）
（2）注册不需要验证用户token，因此改成before_filter :authenticate_user_from_token!,only: [:show,:edit,:update]
（3）参数加入：params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :user_id)
（4）注册成功返回json:{"success": true, token:@user.authentication_token, user_id:@user.id }
         注册失败返回json:{"success": false}
3.curl使用示例：`curl -X POST -H 'Content-Type: application/json' -d '{"user":{"password":"12345678","password_confirmation":"12345678","email": "1sdaf@x.com"}}' http://localhost:8083/api/session/users.json`

**Comment by GreatVincy** [comment]
还有一点：在路由配置里加入了create这一action即：
`namespace :session do
      resources :users, only: [:edit, :show, :update, :create]
 end
`
