### ISSUE TITLE
商品分类树结构

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#36]
1、引入https://github.com/stefankroes/ancestry     
2、新增商品分类模型：rails g scaffold goods_catalog name image level:integer（已执行直接下一步）
3、一级CRUD;
4、二级CRUD：二级界面操作可以选择祖先(ancestry)
5、以及对应的图片上传功能

**Comment by GreatVincy** [comment]
1.提交版本号：
（1）分类模型构建以及CRUD前后端配合实现[https://github.com/sguo2017/tisp_rails_api/commit/69c1533b77c76b7a52c091e871c75a570a5f7f53](url)
（2）禁止root节点编辑[https://github.com/sguo2017/tisp_rails_api/commit/362b6ee9f8bce4ad67df6bde8675e03cd7f4f0da](url)
（3）加入图片上传功能[https://github.com/sguo2017/tisp_rails_api/commit/2c3ae05dc82d0d1275518c06c6416d2d3befe9a9](url)

2.脚本
rails g scaffold goods_catalog name image level:integer
