### ISSUE TITLE
针对商品二级分类相关的商品进行统计

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#37]
返回对应二级类型商品个数
如，一级：教育 二级：语文、数学
统计语文类商品的个数

**Comment by GreatVincy** [comment]
1.提交版本号[https://github.com/sguo2017/tisp_rails_api/commit/27f72defe38e862806679873d2b5fb36a0de7ecd](url)

2.
（1）Good的增、删、改操作都会将数量关联到GoodsCatalog中，GoodsCatalog的删改也会更新到Good的字段（goods_catalog_id）中
（2）GoodsCatalog表中计数属性goods_count默认值必须为0，不然会出错，而且通过rails应用本身是无法修改这个值的
（3）goods_catalog_id、goods_count的名字最好不要随便更改
