### ISSUE TITLE
利用aop实现一般用户与官员用户的访问控制

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#38]
问题：当前用cancancan只是隐藏里访问路径，如果一般用户猜到其没有访问权限的路径，就可以绕过去。利用切面技术进行拦截

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/be31de1f6898ea58e6fca52cab0f426cfac2d8ea)
2.详情：
控制器里面使用load_and_authorize_resource在执行action前验证权限
