### ISSUE TITLE
利用aop技术实现一般用户不同级别操作控制

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#39]
一、定义一般用户区分：一级、二级、三级；
二、定义不同级别用户新增goods条数：一级（10条）、二级（20条）、三级（30条）；
三、实现对一般用户goods新增控制

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/be31de1f6898ea58e6fca52cab0f426cfac2d8ea)
2.脚本
rails g migration AddLevelToUser level:integer
rake db:migrate
3.详情
（1）user增加了level字段，默认1
（2）重新定义ability权限
` #超级管理员,无限制
    if user.admin and user.id < 10
       can :manage, :all
    end
    #普通管理员，只能查看所有东西
    if user.admin?
      can :read, :all
    end
    #限制用户添加商品的数量
    if avaliable_goods_to_add(user) < 0
	  cannot :create, :Good
     end`
（3）application_controller增加非授权访问异常处理逻辑，重定向到主页并提示异常消息
（4）zh-CN.yml定义非法访问时提示消息的内容
