### ISSUE TITLE
加图像交易吗防止暴力访问

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#40]

**Comment by GreatVincy** [comment]
1.提交版本号
功能版本：[链接](https://github.com/sguo2017/tisp_rails_api/commit/3865c5e66cbe5f2206d1397a1f19562f2f128f85)
完善版本：[链接](https://github.com/sguo2017/tisp_rails_api/commit/e95267d5dd19ddbd0e6a6c67b59948a7ec0ea749)

2.注意事项：
（1）使用了RuCaptcha插件，底层机制尚不十分清楚，依赖于ImageMagick。
（2）以后需要使用验证码功能的话可以在view中直接渲染‘devise/shared/rucaptcha’模板，js和css已经在全局配置好，只需在控制器里面加入判断逻辑即可。
