### ISSUE TITLE
（防止撞库）一天只允许3次输错密码，超过3次锁住用户不允许登录

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#41]

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/4ca53ba4d6a07e8f84372c423648bafdf7d02182)
2.脚本
rails g migration AddLockToUsers lock:integer
rake db:migrate
3.说明
加入防撞库功能，密码输入三次当天不能登陆。
其中：
（1）数据库使用lock:integer字段存储密码出错的次数
（2）管理员不受限制
（3）管理员的用户管理界面加入了可以对用户进行锁定、解锁
（4）锁定、解锁相关的操作以及判断逻辑放在user类里面
（5）第二天自动解锁
