### ISSUE TITLE
用户行为记录

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#42]
1、记录用户行为：前一个页面、访问地址、平台（手机端Android|IOS、pc）、浏览器信息、ip地址、经纬度、时间；
2、上述记录要异步提交，不影响用户体验；

**Comment by GreatVincy** [comment]
1.提交版本号
简单信息：[链接](https://github.com/sguo2017/tisp_rails_api/commit/ad07c8a468c53c64794f98c23a746e7bb3a521c5)
逻辑优化后：[链接](https://github.com/sguo2017/tisp_rails_api/commit/d3972f44e59d180103a69094c8f2ed1101ed12cc)
加入地理位置、离开时间：[链接](https://github.com/sguo2017/tisp_rails_api/commit/cc4e8ac3c733e2af069e4e35cbd25d1274aa198c)

2.说明
(0)新增了users_behaviors表存储用户信息
(1)浏览器端所有信息均采用ajax异步提交；
(2)api端可以使用curl访问保存用户信息，例如
    
    新增
curl -X POST -H 'Content-Type: application/json' -d '{"users_behavior":{"user_id":"4", "from_url":"from.test","request_url":"request.test","ip": "1.1.1.1", "os": "ios 9.1","broswer": "Safari 9", "geo_position": "(22.22,22.22)"}}' http://localhost:8083/api/users/users_behaviors  

(3)浏览器端目前尚不能收集鼠标点击坐标
(4)用户离开页面时才会收集地理位置、离开时间信息
(5)js使用了es6 一些API尚不清楚是否存在浏览器兼容性问题
