### ISSUE TITLE
用户、订单、会话没有查询区域

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#43]

**Comment by GreatVincy** [comment]
1.提交版本号
[用户：](https://github.com/sguo2017/tisp_rails_api/commit/a5fbf6f1918aca5ff3739b11c87342cf870750ad)
[订单：](https://github.com/sguo2017/tisp_rails_api/commit/dac4fee75f782dd5e00e3e2f81d37e32163b8dda)
[会话：](https://github.com/sguo2017/tisp_rails_api/commit/de18a11c057b2bbd51b693a91775a7a1c588dd36)

2.脚本
rails g model UsersSearch user_id:integer user_email:string user_name:string is_admin:boolean user_level:integer has_locked:boolean user_created:string
rake db:migrate
rails g controller users_searches --no-assets --no-helper

rails g model OrdersSearch order_id:integer serv_offer_title:string  serv_offer_id:integer offer_user_id:integer request_user_id:integer status:string connect_time:string bidder:integer signature:integer order_created:string
rake db:migrate
rails g controller orders_searches --no-assets --no-helper

rails g model ChatsSearch chat_id:integer order_id:integer chat_content:string  user_id:integer chat_catalog:string chat_created:string 
rake db:migrate
rails g controller chats_searches --no-assets --no-helper
