### ISSUE TITLE
定时任务

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#44]
在libs/tasks

**Comment by sguo2017** [comment]
新建文件
vim clue.rake 

namespace :clue do
  desc "TODO"
  task init: :environment do
        User.create(email:'admin@qq.com', password:'888888')
  end

end

执行
rails clue:init

其他：

**Comment by sguo2017** [comment]
研究下怎么定时执行

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/90f91c2b4b3fdec758fdec2c1989ac0b2f209de0)

2.说明：
（1）使用了[rufus-scheduler](https://github.com/jmettraux/rufus-scheduler)定时任务插件，对外部无依赖，容易编写任务
（2）在/config/initializers文件夹下面添加了clean_search_timer文件，里面定义了使用rufus-scheduler定时清理的代码，目前设定为1小时清除一次（可在const.rb中修改）
（3）清理时创建新的线程去执行数据库操作，出现异常不会影响到服务器以及计时器
（4）rails启动时会执行initializers文件夹下面的文件，因此定时器在rails启动的那一刻开始执行。
