### ISSUE TITLE
系统消息查询api显示增加间隔时间

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#45]
如：
1、1天显示理距离当前间隔小时：1h、2h、…
2、超过24小时显示距离当前间隔天数：1d、2d、…

**Comment by sguo2017** [comment]
if(day(now()-created_at)>1 ){
  1d
  2d
}else{
  1h
  2h
}

取整，向上，如：超过1分钟 则加多1小时，天数同样处理。

interval:间隔

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/825b9dfb447e437bd23bf6d66848cd824b128282)
2.脚本
rails s migration AddIntervalToSysMsgs interval:string
rake db:migrate
3.测试：
（先登录）
curl -X GET -H 'Content-Type: application/json'  http://localhost:8083/api/sys/sys_msgs?token=PzraWSbTDL3zzvSMwD29
