### ISSUE TITLE
登录后保存当前登录的地理位置信息到uses及api

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#46]
t.string   "district"
    t.string   "city"
    t.string   "province"
    t.string   "country"
    t.string   "latitude"
    t.string   "longitude"

**Comment by sguo2017** [comment]
1、登录后要修改更新；
2、注册也要丢过来：

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/3ece9fa85ce2739dfc509c9a8e2e9f0c5fc168a3)
2.脚本
rails g migration AddGeoInfosToUsers district:string,city:string, province:string, country:string, latitude:string, longitude:string
rake db:migrate
3.测试：
登录：
curl -X POST -H 'Content-Type: application/json' -d '{"user":{"password":"zzzzzz","password_confirmation":"zzzzzz","email": "p3sa@qq.com","district":"test", "city":"test","province":"test", "country":"test", "latitude":"test", "longitude":"test"}}' http://localhost:8083/api/users/sessions
注册：
curl -X POST -H 'Content-Type: application/json' -d '{"user":{"password":"123456","password_confirmation":"123456","email": "testtest@qq.com","district":"test", "city":"test","province":"test", "country":"test", "latitude":"test", "longitude":"test"}}' http://localhost:8083/api/users/registrations
