### ISSUE TITLE
完善消息（sys_msgs）新增

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#47]
字段一（新增）msg_catalog：消息类型(00A:个人私有消息；00B:个人私有由系统推送消息；00C:公共消息)；
字段二（已有）user_id：新建人id；
字段三（现在）accept_user_id：接受者id；
字段四（新增）status：00A:新建，未读；00B:已读，丢弃；00C:已读，接受——修改成“语义化”
字段五（新增）goods_id：记录goods_id

msg_catalog数据产生说明：
场景00A：莫人新增goods[serv_catagory=serv_request]，由系统向同城人新建一条此类型的数据，user_id=新增人，accept_user_id=推送同城人；
场景00B : 在pc端由管理员新建消息，发布范围：所有人、按区域选择接受人
场景00C : 
新用户注册产生一条数据action_title=加入奇客（此定义成常量），action_desc=自我简介（[补]users要加一个自我简介字段profile）；
用户新增一条goods[serv_catagory=serv_offer]数据action_title=发布了一项专项服务（此定义成常量），action_desc=goods.detail；
用户新增1条订单（订单状态00A）时action_title= 正在了解XXX专业服务（此定义成常量XXX使用时进行替换），action_desc=空；
订单状态00B时action_title= 正在与XXX沟通一个工作机会（此定义成常量XXX使用时进行替换），action_desc=用户名；订单状态00C时action_title= 与XXX达成一个工作机会（此定义成常量XXX使用时进行替换），action_desc=用户名；

**Comment by GreatVincy** [comment]
1.提交版本号
早前版本：[链接](https://github.com/sguo2017/tisp_rails_api/commit/01cb7509664d43024f6d9fd0e311ea3ed3e1d42c)
完善版本：[链接](https://github.com/sguo2017/tisp_rails_api/commit/09b20c1f70200adba88c423d63039c5014f82914)
2.脚本
rails g model SysMsgsTimelines user_id:integer:index sys_msg_id:integer
3.说明
（1）基本上是使用ActiveRecord的回调函数进行事件的处理，在Model层进行处理，除了00B场景要调用一个set_accept_user(param)方法传入指定的城市或用户之外，其他的场景均不用经过Controller处理，API端使用也可以触发相应的事件。
（2）消息和用户之间是多对多关系，使用中间表sys_msgs_timelines进行关联。
（2）SysMsg、User对象删除时，中间表中的关联对象也被删除；反过来则不成立。
