### ISSUE TITLE
完善消息（sys_msgs）查询 API

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#48]
针对msg_catalog三中场景进行查询：
> 场景00A：某人新增goods[serv_catagory=serv_request]，由系统向同城人新建一条此类型的数据,**user_id=新增人，accept_user_id=推送同城人；**  

>  场景00B : 在pc端由管理员新建消息，发布范围：所有人、按区域选择接受人  

>  场景00C :
> (1) 新用户注册产生一条数据action_title=加入奇客（此定义成常量），action_desc=自我简介（[补]users要加一个自我简介字段profile）；
> (2)用户新增一条goods[serv_catagory=serv_offer]数据，action_title=发布了一项专项服务（此定义成常量），action_desc=goods.detail；
> (3)用户新增1条订单（订单状态00A）时，action_title= 正在了解XXX专业服务（此定义成常量XXX使用时进行替换），action_desc=空；
> 订单状态00B时，action_title= 正在与XXX沟通一个工作机会（此定义成常量XXX使用时进行替换），action_desc=用户名；  
> 订单状态00C时，action_title= 与XXX达成一个工作机会（此定义成常量XXX使用时进行替换），action_desc=用户名；

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/ef28b15253248f6f6da2e38a535edb5903d9099a)
2.说明：
可以直接使用curl命令执行查询，例如

    curl -X GET -H 'Content-Type: application/json'  http://localhost:3000/api/sys_msgs_timelines/sys_msgs_queries?query_type=0\&user_id=4\&page=1
其中query_type以及user_id是必须参数，否则返回  

    status: :failed,reason: :parameters_error

query_type以及user_id无效时也会返回上面的信息。
query_type有一下4中类型：
> A|a|1 ：对应场景00A
> B|b|2 ：对应场景00B
> C|c|3 ：对应场景00C
> ALL|all|0 ：得到全部信息

**注意：curl命令中如果链接中使用了&符号连接多个参数，必须使用\进行转义，否则会被识别为系统命令**
