### ISSUE TITLE
通过邮箱重置密码API

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#49]
1、暂时配置邮箱，直接提交代码
qike2018qike@163.com
cc111111
2、发重置的密码到用户注册的邮箱中；
3、发送邮件注意下个格式

**Comment by sguo2017** [comment]
<div><br></div><div><includetail><div><br></div><div><br></div><div style="font-size: 12px;font-family: Arial Narrow;padding:2px 0 2px 0;">------------------&nbsp;原始邮件&nbsp;------------------</div><div style="font-size: 12px;background:#efefef;padding:8px;"><div><b>发件人:</b>&nbsp;"前程无忧(51job)";&lt;service@51job.com&gt;;</div><div><b>发送时间:</b>&nbsp;2016年3月26日(星期六) 中午11:56</div><div><b>收件人:</b>&nbsp;"gs"&lt;sguo08@qq.com&gt;; <wbr></div><div></div><div><b>主题:</b>&nbsp;[51job] 请查收您的密码  </div></div><div><br></div>


<style type="text/css">
body 
{    
	 line-height:20px;
   font-size:12px;
	 font-family:"宋体";
   margin:0px;
   padding:0px;
   color:#5c5c5c;
}

#container {
     width:666px;
     margin:0 auto;
}
 
img {
     border:0;
}

a.toplink:link, a.toplink:visited 
{
color:#777;
text-decoration:none;
font-size:12px;
font-family:"宋体";
}

a.toplink:hover 
{
color:red;
text-decoration:none;
font-size:12px;
font-family:"宋体";
}

.cEmail a:link,.cEmail a:visited 
{
	color:#ec7608;
}
.cEmail a:hover 
{
	color:red;
}

a:link {
color:#ff7300;
font-size:14px;
font-family:"宋体";
text-decoration:underline;
}

a:visited {
color:#ff7300;
font-size:14px;
font-family:"宋体";
text-decoration:underline;  
}

a:hover {
color:#ff7300;
font-size:14px;
font-family:"宋体";
text-decoration:underline;
}

.boxorg{
border:#FF6600 solid 1px;
}

.top_org{
background:url(http://images.51job.com/im/2009/mailcenter/template/top_org.gif) no-repeat;
text-align:left;
width:592px;
height:25px;
line-height:25px;
} 

.wttitlt{
font-size:14px;
color:#FFFFFF;
text-align:left;
font-weight:bold;
padding:0 0 0 10px;
}

.wt{
color:#FFFFFF;
text-align:right;
padding:0 10px 0 0;
}

a.wt:link{
color:#FFFFFF;
text-align:right;
padding:0 10px 0 0;
font-size:12px;
font-family:"宋体";
}

a.wt:hover{
color:#FFFFFF;
text-align:right;
padding:0 10px 0 0;
font-size:12px;
font-family:"宋体";
}

a.wt:visited{
color:#FFFFFF;
text-align:right;
padding:0 10px 0 0;
font-size:12px;
font-family:"宋体";
}

.k2_m{
background:url(http://images.51job.com/im/2009/mailcenter/template/k2_m.gif) no-repeat;
width:609px;
}

a.daray:link, a.daray:visited {
color:#333333;
font-size:12px;
font-family:"宋体";
text-decoration:underline;
}     

a.daray:hover {
color:red;
font-size:12px;
font-family:"宋体";
text-decoration:underline;
}
</style>




<p>&nbsp;</p>
<div id="container">
<table height="54" background="http://img01.51jobcdn.com/im/2009/mailcenter/template/topbg.gif" width="660" border="0" cellspacing="0" cellpadding="0" style="color:#777; font-size:12px;">
        <tbody><tr>
          <td valign="bottom" align="center" width="120" style="padding-bottom:5px;"><img src="http://img01.51jobcdn.com/im/2009/mailcenter/template/51joblogo.gif"></td>
          <td valign="bottom" align="center" width="1" style="padding-bottom:5px;"><img src="http://img01.51jobcdn.com/im/2009/mailcenter/template/line.gif"></td>
          <td valign="bottom" align="center" width="93" style="padding-bottom:5px;"><img src="http://img01.51jobcdn.com/im/2009/mailcenter/template/toptitle8.gif" width="73" height="22"></td>
          <td>&nbsp;</td>
          <td valign="bottom" align="center" width="55" style="padding-bottom:5px;"><a target="_blank" href="http://my.51job.com/my/mailtrace/mailtrace.php?t=4" class="toplink">才市情报</a></td>
          <td valign="bottom" align="center" width="10" style="padding-bottom:5px;">|</td>
          <td valign="bottom" align="center" width="55" style="padding-bottom:5px;"><a target="_blank" href="http://my.51job.com/my/mailtrace/mailtrace.php?t=4" class="toplink">工作机会</a></td>
          <td valign="bottom" align="center" width="10" style="padding-bottom:5px;">|</td>
          <td valign="bottom" align="center" width="55" style="padding-bottom:5px;"><a target="_blank" href="http://my.51job.com/my/mailtrace/mailtrace.php?t=4" class="toplink">培训充电</a></td>
        </tr>
        <tr>
          <td height="16" colspan="9" align="center" valign="bottom" style="padding-bottom:5px;"></td>
        </tr>
  </tbody></table>
      
<table width="660" border="0" cellspacing="0" cellpadding="0">
  <tbody><tr>
    <td><img src="http://img01.51jobcdn.com/im/2009/mailcenter/template/bgtop.gif" width="660" height="19"></td>
  </tr>
  <tr>
    <td background="http://img01.51jobcdn.com/im/2009/mailcenter/template/bgmidd.gif">	
	      <table width="609" border="0" align="center" cellpadding="2" cellspacing="5" style=" font-size:12px ">
      <tbody><tr>
        <td align="center"><img src="http://img01.51jobcdn.com/im/2009/mailcenter/template/getpwd.gif"></td>
        </tr>
      <tr>
            <td align="left" valign="middle" style="font-size: 14px;line-height: 22px;"><strong>亲爱的会员，您好！</strong></td>
      </tr> 
</tbody></table>

<table width="636" border="0" cellspacing="0" cellpadding="0" align="center">
  <tbody><tr>
    <td><img src="http://img01.51jobcdn.com/im/2009/mailcenter/template/kuangtop.gif"></td>
  </tr>
  <tr>
    <td background="http://img01.51jobcdn.com/im/2009/mailcenter/template/kuangmidd.gif">
    <table width="592" border="0" align="center" cellpadding="0" cellspacing="0" style="font-size: 14px">
            <tbody><tr>
              <td height="29">&nbsp;</td>
              <td align="left">以下是您的密码信息,请查收:</td>
              </tr>
			<tr>
<td>&nbsp;</td>
<td height="70"><strong>您的会员名</strong>:gs81825818<br>
<a href="http://my.51job.com/my/My_ResetPassword.php?resettoken=ADoGbgFhBTIGYwplBGZTZw1yUDZWI1c6VGMFbwszDzoJOQBqA2kDeVQ0CGBQMAQ/AjgLPFZkUjEANlE3">请点击此链接重置您的密码</a><p style="word-break:break-all;font-size:12px;">如果该链接无效， 请直接复制以下的链接：<br>
http://my.51job.com/my/My_ResetPassword.php?resettoken=ADoGbgFhBTIGYwplBGZTZw1yUDZWI1c6VGMFbwszDzoJOQBqA2kDeVQ0CGBQMAQ/AjgLPFZkUjEANlE3</p><strong>您的邮件</strong>:sguo08@qq.com
</td>
</tr>
            <tr>
              <td colspan="2" align="center">
			  <table width="100%" border="0" cellpadding="0" cellspacing="0">
                <tbody><tr>
                  <td height="2" bgcolor="#FF7300"></td>
                </tr>
              </tbody></table>
                </td>
            </tr>
            <tr>
              <td colspan="2" align="left" valign="top" style="font-size: 12px"><p><br>
                  如果您在使用过程中遇到任何问题，您可以写信给我们:<a href="mailto:service@51job.com">service@51job.com</a> 或者拨打我们 的会员服务专线: 800-820-5100 与我们联系，我们会尽快为您解决。</p></td>
            </tr>            
          </tbody></table>	
    
    </td>
  </tr>
  <tr>
    <td><img src="http://img01.51jobcdn.com/im/2009/mailcenter/template/kuangbott.gif"></td>
  </tr>
</tbody></table>   
 <table width="633" border="0" align="center" cellpadding="3" cellspacing="0" style=" font-size:12px ">
              <tbody><tr>
                <td><span style="margin-left:20px;">希望您能继续关注我们。您的支持是我们前进的最大动力。谢谢！</span></td>
              </tr>
              <tr>
                <td align="right">前程无忧51job</td>
              </tr>
        </tbody></table>
	  </td>
    </tr>
  <tr>
    <td background="http://img01.51jobcdn.com/im/2009/mailcenter/template/bgmidd.gif"><img src="http://img01.51jobcdn.com/im/2009/mailcenter/template/bgbottom.gif" width="660" height="19"></td>
  </tr>
  </tbody></table>
         
         
<table></table>

<table width="666" border="0" cellspacing="0" cellpadding="0" style="font-family:Arial;font-size:12px;">
        <tbody><tr>
          <td height="15" valign="middle" align="center"><div style="border-top:1px solid #FF6600; height:2px; line-height:2px;"></div></td>
        </tr>
        
        <tr>
          <td align="center" height="20" valign="middle" class="cEmail">加入前程无忧Club，请垂询：800-820-5100 或 Email：<a target="_blank" href="mailto:Club@51job.com" style="text-decoration:none;">Club@51job.com</a></td>
        </tr>
        <tr>
          <td align="center" height="20" valign="middle">无忧工作网版权所有©1999-2016</td>
        </tr>
</tbody></table>
</div></includetail></div>

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/8dd644f9d3e3a212684204e34f9f522552dbe28d)

2.说明：
（1）提供的邮箱有问题（可能是安全设置）不能发送，换成我自己的可以
（2）重置密码只能在网页端进行（邮件中包含链接）
（3）API端可以调用发送重置密码的邮件的功能
curl示例：
> curl -X POST -H 'Content-Type: application/json' -d '{"user":{"email":"18520788695@163.com"}}' 
> http://localhost:8083/api/users/passwords
( 4 )要更改邮箱账号，只需在Const中更改两个常量即可，但如果要更改协议、端口、邮件服务器域名等还需要在environment目录下相应的配置文件中修改。
