### ISSUE TITLE
完善消息（sys_msgs）查询 API

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#50]
没有tocken拦截

**Comment by zengkm** [comment]
返回数据没有用户头像

**Comment by zengkm** [comment]
没有定义取消的状态

**Comment by sguo2017** [comment]
提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/a519b6c5b34444364d5d705c499d99858b966c81)
