### ISSUE TITLE
美化主界面

### ISSUE THREAD

**Issue by sguo2017** [sguo2017/tisp_rails_api#8]
1、bootstarp格式化
2、国际化 
3、自有layout

**Comment by GreatVincy** [comment]
1.提交[版本号](https://github.com/sguo2017/tisp_rails_api/commit/36fb1a738a696410d907e8ab989fca07a4cf659a)
2.脚本rails g kaminari:config 、rails g kaminari:views bootstrap3、rails g bootstrap:themed Pages
